<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'brera\\poc\\edgetoedgetest' => '/Integration/EdgeToEdgeTest.php',
                'brera\\poc\\inmemorydomaineventqueuetest' => '/Unit/InMemoryDomainEventQueueTest.php',
                'brera\\poc\\inmemoryproductrepositorytest' => '/Unit/InMemoryProductRepositoryTest.php',
                'brera\\poc\\productidtest' => '/Unit/ProductIdTest.php',
                'brera\\poc\\producttest' => '/Unit/ProductTest.php',
                'brera\\poc\\skustub' => '/Integration/stubs/SkuStub.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
