<?php
/**
 * @var \LizardsAndPumpkins\Renderer\Block $this
 */
?>
<div class="footer-container">
    <div class="footer">
        <div class="footer-block">
            <div class="footer-block-title">21run.com</div>
            <ul id="footer-list-about">
                <li><a href="<?= $this->getBaseUrl() ?>about-us">Über uns</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>affiliate-program">Partnerprogramm</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>terms-conditions">AGB</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>data-protection">Datenschutz</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>cancellation">Widerrufsbelehrung</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>imprint">Impressum</a></li>
            </ul>
        </div>
        <div class="footer-block">
            <div class="footer-block-title">Kundenservice</div>
            <ul>
                <li><a href="<?= $this->getBaseUrl() ?>contacts">Kontakt</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>service">Unser Service</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>shipping">Versand</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>groessentabelle">Größen-Kompass</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>exchange">Rücksendung / Umtausch</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>faq">FAQ</a></li>
            </ul>
        </div>
        <div class="footer-block">
            <div class="footer-block-title">Mein Konto</div>
            <ul>
                <li><a href="<?= $this->getBaseUrl() ?>customer/account">Mein Konto</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>sales/order/history">Lieferstatus</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>newsletter">Newsletter</a></li>
            </ul>
        </div>
        <div class="footer-block-wide">
            <img src="<?= $this->getBaseUrl() ?>images/footer-banner-newsletter.png" alt="" />
            <img src="<?= $this->getBaseUrl() ?>images/footer-payment-methods.png" alt="" />
        </div>
        <div class="footer-block-info">
            <p>
                Alle Preise verstehen sich inkl. MwSt. und zzgl. Versandkosten. Bei "statt"-Preisen handelt es sich um
                die unverbindliche Preisempfehlung des Herstellers.<br/>
                Anbieterkennzeichnung: 21run.com ist ein Angebot der L&S Lauf- & Sport Shop GmbH, Saarburger Ring 19-21,
                68229 Mannheim - Kundenservice - weitere Angaben im Impressum.
            </p>
        </div>
    </div>
</div>
