<div class="footer-container">
    <div class="footer">
        <div class="footer-block">
            <div class="footer-block-title">21run.com</div>
            <ul id="footer-list-about">
                <li><a href="/ru_de/about-us">Über uns</a></li>
                <li><a href="/ru_de/affiliate-program">Partnerprogramm</a></li>
                <li><a href="/ru_de/terms-conditions">AGB</a></li>
                <li><a href="/ru_de/data-protection">Datenschutz</a></li>
                <li><a href="/ru_de/cancellation">Widerrufsbelehrung</a></li>
                <li><a href="/ru_de/imprint">Impressum</a></li>
            </ul>
        </div>
        <div class="footer-block">
            <div class="footer-block-title">Kundenservice</div>
            <ul>
                <li><a href="/ru_de/contacts">Kontakt</a></li>
                <li><a href="/ru_de/service">Unser Service</a></li>
                <li><a href="/ru_de/shipping">Versand</a></li>
                <li><a href="/ru_de/groessentabelle">Größen-Kompass</a></li>
                <li><a href="/ru_de/exchange">Rücksendung / Umtausch</a></li>
                <li><a href="/ru_de/faq">FAQ</a></li>
            </ul>
        </div>
        <div class="footer-block">
            <div class="footer-block-title">Mein Konto</div>
            <ul>
                <li><a href="/ru_de/customer/account">Mein Konto</a></li>
                <li><a href="/ru_de/sales/order/history">Lieferstatus</a></li>
                <li><a href="/ru_de/newsletter">Newsletter</a></li>
            </ul>
        </div>
        <div class="footer-block-wide">
            <p align="center">
                <img src="images/footer-banner-newsletter.png" alt="" />
                <img src="images/footer-payment-methods.png" alt="" />
            </p>
        </div>
        <div class="footer-block-info">
            <p>Alle Preise verstehen sich inkl. MwSt. und zzgl. Versandkosten. Bei "statt"-Preisen handelt es sich um
                die unverbindliche Preisempfehlung des Herstellers.<br/>Anbieterkennzeichnung: L&amp;S Lauf- &amp; Sport
                Shop GmbH, Saarburger Ring 19-21, 68229 Mannheim - Kundenservice - weitere Angaben im Impressum.</p>
            <p>&nbsp;</p>
            <p>Neue Laufschuhe günstiger einkaufen bei 21run.com</p>
            <p>Wir sind der Online-Shop für alle Läufer, die auf der Suche nach einem preiswerten Laufschuh-Angebot
                sind. Bei uns können Sie aktuelle Laufschuhe der Marken Asics, Brooks, Nike, Mizuno und New Balance bis
                zu 38% günstiger kaufen als in einem regulären Laufladen wie z. B. in unserem <a
                    href="/about-us">Laufshop in Mannheim</a>. Der Unterschied bei unserem Angebot
                im Web ist, dass Sie bei einem Onlinekauf keine Beratungsleistung in Anspruch nehmen und Sie dadurch
                einiges sparen können. Vorausgesetzt Sie wissen, was Sie wollen und welcher Laufschuhschuh für Sie gut
                ist. Sie wissen also, welche Runningschuhe perfekt für Sie sind und haben schon einen digitalen
                Fußabdruck oder ein biomechanisches Profil erstellen lassen? Dann sind Sie richtig bei uns! Hier können
                Sie ihre Laufschuhe billig kaufen und erhaltent trotzdem die beste Qualität. Die Bestellung ist simpel:
                Durch unsere vollautomatisierte Bestellannahme und Zahlungsabwicklung können Sie sehr schnell und sicher
                günstige Laufschuhe kaufen. Nachdem Sie Ihr Modell gewählt haben, können Sie einfach per Mausklick über
                einen elektronischen Warenkorb bestellen und bequem und sicher per Banküberweisung oder Kreditkarte
                bezahlen. Bei 21run.com bequem einkaufen und in nur wenigen Tagen mit neuen Laufschuhen trainieren.</p>
            <p>Sollten Sie in unserem Shop mal nicht ihr gewünschtes Modell finden, können Sie gerne mit uns Kontakt
                aufnehmen. Viel Spaß beim Laufschuh-Kauf!</p>
            <p>&nbsp;</p>
            *Bis zum 01.02.2015 erhalten Sie ab einem Mindestbestellwert von 129,95 Euro, mit dem Gutscheincode
            „21RUN-17“, einen Rabatt von 17,00 Euro. Der Code muss bei der Bestellung im Warenkorb eingegeben werden.
            Jeder Gutschein-Code kann pro Kunde mehrfach eingelöst werden. Keine Auszahlung oder Kombination mit anderen
            Gutscheinen möglich. Wird der Mindestbestellwert durch einen nachträglichen Widerruf ihrer Bestellung
            unterschritten, verliert der Gutschein seine Gültigkeit und es erfolgt eine Rückrechnung des Rabattes.
        </div>
    </div>
</div>
