<?php
/**
 * @var \Brera\Product\Block\ProductImageGallery $this
 */
?>
<?php

$mainImage = $this->getMainProductImage();

?>
<div class="main-image-area-wrapper">
    <div id="wrap" style="top:0; position:relative">
        <a id="main-image" href="<?php echo $mainImage->getSrc() ?>" class="main-image-area image-zoom cloud-zoom" rel="" style="cursor: move; position: relative; display: block;"><img src="<?php echo $mainImage->getSrc() ?>" height="340" width="365" itemprop="image"  alt="<?php echo $mainImage->getLabel() ?>"/></a>
        <div class="mousetrap" style="z-index: 9; position: absolute; width: 365px; height: 340px; left: 0; top: 0; cursor: move;"></div>
    </div>
</div>
<div class="more-views">
    <ul>
        <li>
            <a href="http://www.21run.com/media/catalog/product/cache/4/thumbnail/9df78eab33525d08d6e5fb8d27136e95/2/0/2013_pro_touch_118235-251.jpg" title="" class="cloud-zoom-gallery" rel="useZoom: 'main-image', smallImage: 'http://www.21run.com/media/catalog/product/cache/4/thumbnail/365x340/9df78eab33525d08d6e5fb8d27136e95/2/0/2013_pro_touch_118235-251.jpg' "><img src="http://www.21run.com/media/catalog/product/cache/4/thumbnail/48x/9df78eab33525d08d6e5fb8d27136e95/2/0/2013_pro_touch_118235-251.jpg" width="48" height="48" title=""/></a>
        </li>
    </ul>
</div>
