<?php
/**
 * @var \LizardsAndPumpkins\Renderer\Block $this
 */
?>
<header class="header-container">
    <?= $this->getChildOutput('content_block_cms_header_info_banner') ?>
    <div class="header">
        <div class="header-panel">
            <a href="<?= $this->getBaseUrl() ?>checkout/onepage/"><?= $this->__('Checkout') ?></a>
            <span class="sep"></span>
            <a href="<?= $this->getBaseUrl() ?>checkout/cart/">
                <strong>
                    <?php /* TODO: Handle pural form */ ?>
                    <span id="meta-menu-cart-num-items">0</span> <?= $this->__('Items') ?> <span id="meta-menu-cart-total">0,00 €</span>
                </strong>
            </a>
            <span class="sep"></span>
            <a href="<?= $this->getBaseUrl() ?>customer/account/"><?= $this->__('My Account') ?></a>
            <span class="sep"></span>
            <a href="<?= $this->getBaseUrl() ?>customer/account/" id="meta-menu-login-link"><?= $this->__('Login') ?></a>
            <a href="<?= $this->getBaseUrl() ?>customer/account/logout/" id="meta-menu-logout-link"><?= $this->__('Logout') ?></a>
        </div>
        <div class="logo">
            <strong>21run.com</strong>
            <a href="<?= $this->getBaseUrl() ?>" title="21run.com"><img src="<?= $this->getBaseUrl() ?>images/logo_fr.png" alt="21run.com"/></a>
        </div>
        <div id="searchPanel">
            <form autocomplete="off" action="<?= $this->getBaseUrl() ?>catalogsearch/result/" class="search-form">
                <div class="input-box">
                    <input id="search" type="text" name="q" maxlength="128" placeholder="<?= $this->__('Enter search keyword') ?>"/>
                    <button type="submit" disabled="disabled" class="disabled">
                        <span class="search-button-image"></span>
                    </button>
                    <div id="search-autosuggestion"></div>
                </div>
            </form>
        </div>
        <script>

            if (typeof eKomiIntegrationConfig == 'undefined') {
                var eKomiIntegrationConfig = new Array({
                    certId: 'DDD129738550E88',
                    sealTargets: [],
                    widgetTargets: []
                });
            }

            eKomiIntegrationConfig[0].sealTargets.push('ekomiSeal130453');

        </script>
        <div id="ekomiSeal130453" class="ekomi-seal"></div>
        <div class="cms_header_small">
            <?= $this->getChildOutput('content_block_cms_header_small') ?>
        </div>
        <ul id="phone-meta-menu">
            <li><a href="<?= $this->getBaseUrl() ?>customer/account/"><img src="<?= $this->getBaseUrl() ?>images/icon-phone-account.png" alt=""/></a></li>
            <li><a href="<?= $this->getBaseUrl() ?>checkout/cart/"><img src="<?= $this->getBaseUrl() ?>images/icon-phone-cart.png" alt=""/></a></li>
            <li class="active"><a href="#" data-block="search"><img src="<?= $this->getBaseUrl() ?>images/icon-phone-search.png" alt=""/></a></li>
        </ul>
        <div id="phone-meta-menu-content" class="search">
            <form autocomplete="off" action="<?= $this->getBaseUrl() ?>catalogsearch/result/" class="search-form">
                <div class="input-box">
                    <input id="search" type="text" name="q" maxlength="128" placeholder="<?= $this->__('Enter search keyword') ?>"/>
                    <button type="submit" disabled="disabled" class="disabled">
                        <span class="search-button-image"></span>
                    </button>
                    <div id="search-autosuggestion"></div>
                </div>
            </form>
        </div>
        <?= $this->getChildOutput('content_block_top-menu') ?>
    </div>
</header>
