<?php
/**
 * @var \LizardsAndPumpkins\Renderer\Block $this
 */
?>
<?= $this->getChildOutput('product_listing_content_block_top') ?>
<div class="toolbar roundedBorder">
    <p class="amount"> <?= $this->__('Item(s)') ?></p>
    <div class="sort-by"><label><?= $this->__('Sort By') ?></label></div>
    <div class="limiter"><label><?= $this->__('Items') ?>: </label></div>
</div>
<div id="products-grid-container"></div>
<div id="pagination"></div>
<script>
    var productListingJson = {{snippet product_grid}},
        productPrices = {{snippet product_prices}},
        totalNumberOfResults = {{snippet total_number_of_results}},
        productsPerPage = {{snippet products_per_page}},
        sortOrderConfig = {{snippet sort_order_config}},
        attributeTranslation = {{snippet attribute_translation}},
        baseUrl = '<?= $this->getBaseUrl() ?>';
</script>
