<?php
/**
 * @var \LizardsAndPumpkins\Product\Block\ProductBlock $this
 */
use LizardsAndPumpkins\Product\ConfigurableProductJsonSnippetRenderer;

?>
<?php

$maxQty = 5; // Temporary hardcoded
$brand = $this->getFirstValueOfProductAttribute('brand');
$brandLogo = strtolower(preg_replace('/\W/', '_', trim($brand))) . '.png';

$productImageCount = $this->getProductImageCount();

/* TODO: Implement calculation of save */
$save = 0;

?>
<div itemscope itemtype="http://schema.org/Product">
    <div class="product-essential">
        <div id="phoneTitlePlaceholder"></div>
        <div class="product-img-box">
            <a href="media/product/original/<?= $this->getMainProductFileName() ?>" class="main-image-area">
                <img src="media/product/large/<?= $this->getMainProductFileName() ?>" itemprop="image" alt="<?= $this->getMainProductImageLabel() ?>"/>
            </a>
            <ul class="more-views">
                <?php for ($i=0; $i<$productImageCount; $i++) : ?>
                    <li>
                        <a href="media/product/original/<?= $this->getProductImageFileNameByNumber($i) ?>" data-image="media/product/large/<?= $this->getProductImageFileNameByNumber($i) ?>"><img src="media/product/small/<?= $this->getProductImageFileNameByNumber($i) ?>" width="48" height="48"/></a>
                    </li>
                <?php endfor ?>
            </ul>
        </div>
        <div class="product-shop">
            <div class="top">
                <div class="product-title">
                    <img src="images/logos/<?= $brandLogo ?>" width="95" id="brandLogo" />
                    <h1 itemprop="name"><?= $this->getFirstValueOfProductAttribute('name') ?></h1>
                    <p class="similarProducts">
                        <?= $this->__('More by') ?> <a href="" itemprop="brand"><?= $brand ?></a>
                    </p>
                </div>
                <div class="articleInformations">
                    <p class="articleNumber"><?= $this->__('SKU# ') ?> <?= $this->getProductId() ?></p>
                    <meta itemprop="sku" content="<?= $this->getProductId() ?>" />
                </div>

                <div class="socialSharing en_US">
                    <div class="item twitterLike"><a href="https://twitter.com/share" class="twitter-share-button">Tweet</a></div>
                    <div class="item g-plusone" data-size="medium"></div>
                    <div class="item fb-like" data-href="<!--= $this->getProductUrl($_product) -->" data-send="true" data-layout="button_count" data-width="200" data-show-faces="false" data-action="recommend"></div>
                    <div class="item print"><a href="javascript:" onclick="window.print()"><?= $this->__('Print') ?> <img src="images/icons/printico.gif" alt="print" /></a></div>
                </div>
            </div>

            <div class="product-main-info">
                <div class="main-information">
                    <?php if ($gender = $this->getImplodedValuesOfProductAttribute('gender', ', ')) : ?>
                        <p><strong><?= $this->__('Gender') ?>:</strong> <?= $gender ?></p>
                    <?php endif ?>

                    <?php if (($style = $this->getImplodedValuesOfProductAttribute('style', ', '))) : ?>
                        <p><strong><?= $this->__('Style') ?>:</strong> <?= $style ?></p>
                    <?php endif ?>

                    <p>
                        <strong><?= $this->__('Availability:') ?> </strong>
                        <span class="availability"><?= $this->__('In Stock') ?></span>
                        <span class="info"><?= $this->__('Versandinfo'); ?></span>
                    </p>
                </div>

                <div class="price-information" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
                    <span class="regular-price"><?= $this->getChildOutput('price') ?></span>
                </div>
                <span class="regular-price"><?= $this->getChildOutput('special_price') ?></span>
            </div>

            <div class="product-controls">
                <input type="hidden" name="product" value="<?= $this->getProductId() ?>"/>
                <div class="selects"></div>
                <button disabled="disabled"><?= $this->__('Add to Cart') ?></button>
            </div>
        </div>
    </div>

    <?= $this->getChildOutput('all-models') ?>

    <div class="product-collateral">
        <ul class="tabs">
            <li><a href="#description"><?= $this->__('Description') ?></a></li>
            <li><a href="#additional-information"><?= $this->__('Additional Information') ?></a></li>
        </ul>
        <div id="description" class="tab-content" itemprop="description">
            <?= $this->getFirstValueOfProductAttribute('description') ?>
        </div>
        <div id="additional-information" class="tab-content">
            [ TODO ]
        </div>
    </div>

    <div id="recently-viewed-products">
        <div class="heading"><?= $this->__('Your Recently Viewed') ?></div>
        <div class="swipe-container"></div>
    </div>

    <script type="text/javascript">

        var html = '<li style="background-image:url(\'/media/brands/brands-small/<?= $brandLogo ?>\')" class="item">';
        html += '<div class="grid-cell-container">';
        html += '<a href="<?php /* TODO: Product URL */ ?>" class="product-image"><img src="media/product/medium/<?= $this->getMainProductFileName() ?>" width="188" height="115" alt="<?= $this->getMainProductImageLabel() ?>" /></a>';
        html += '<h2 class="product-name"><a href="<?php /* TODO: Product URL */ ?>"><?= $this->getFirstValueOfProductAttribute('name') ?></a></h2>';
        html += '<a href="<?php /* TODO: Product URL */ ?>"><?= $this->getChildOutput('price') ?></a>';
        <?php if ($gender) : ?>
        html += '<p class="product-category"><a href="<?php /* TODO: Product URL */ ?>"><?= is_array($gender) ? implode(',', $gender) : $gender ?></a></p>';
        <?php endif; ?>
        <?php if ($save > 0) : ?>
        html += '<p class="you-save"><a href="<?php /* TODO: Product URL */ ?>"><?= sprintf($this->__('You save %s'), '<strong>' . $save . '%</strong>') ?></a></p>';
        <?php endif; ?>
        html += '</div>';
        html += '</li>';

        var product = {sku: '<?= $this->getProductId() ?>', html: html};
        var variation_attributes = <?= $this->getChildOutput(ConfigurableProductJsonSnippetRenderer::VARIATION_ATTRIBUTES_CODE) ?>;
        var associated_products = <?= $this->getChildOutput(ConfigurableProductJsonSnippetRenderer::ASSOCIATED_PRODUCTS_CODE) ?>;

    </script>
</div>

<div id="fb-root"></div>
