<?php
/**
 * @var \Brera\Product\Block\ProductDetailsPageBlock $this
 */
?>
<?php

$maxQty = 5; // Temporary hardcoded
$brand = $this->getProductAttributeValue('brand');
$brandLogo = strtolower(preg_replace('/\W/', '_', trim($brand))) . '.png';

/* TODO: Implement calculation of save */
$save = 0;

?>
<div id="productView" class="configurable" itemscope itemtype="http://schema.org/Product">
    <form action="<?php /* TODO: Implement */ ?>" method="post" id="product_addtocart_form">
        <div class="no-display">
            <input type="hidden" name="product" value="<?= $this->getProductId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        <div class="product-essential">
            <div class="product-img-box">
                <?= $this->getChildOutput('image_gallery') ?>
            </div>
            <div class="product-shop">
                <div class="top">
                    <div class="product-title">
                        <img src="images/logos/<?= $brandLogo ?>" width="95" />
                        <div class="product-title-info">
                            <h1 itemprop="name"><?= $this->getProductAttributeValue('name') ?></h1>
                            <p class="similarProducts">
                                <?= $this->__('More by') ?> <a href="" itemprop="brand"><?= $brand ?></a>
                            </p>
                        </div>
                    </div>
                    <div class="articleInformations">
                        <p class="articleNumber"><?= $this->__('SKU# ') ?> <?= $this->getProductId() ?></p>
                        <meta itemprop="sku" content="<?= $this->getProductId() ?>" />
                    </div>

                    <div class="socialSharing en_US">
                        <div class="item twitterLike"><a href="https://twitter.com/share" class="twitter-share-button">Tweet</a></div>
                        <div class="item g-plusone" data-size="medium"></div>
                        <div class="item fb-like" data-href="<!--= $this->getProductUrl($_product) -->" data-send="true" data-layout="button_count" data-width="200" data-show-faces="false" data-action="recommend"></div>
                        <div class="item print"><a href="javascript:" onclick="window.print()"><?= $this->__('Print') ?> <img src="images/icons/printico.gif" alt="print" /></a></div>
                    </div>
                </div>

                <div class="product-main-info">
                    <div class="main-information">
                        <?php if ($gender = $this->getProductAttributeValue('gender')) : ?>
                            <p><strong><?= $this->__('Gender') ?>:</strong> <?= $gender ?></p>
                        <?php endif ?>

                        <?php if (($style = $this->getProductAttributeValue('style'))) : ?>
                            <p><strong><?= $this->__('Style') ?>:</strong> <?= $style ?></p>
                        <?php endif ?>

                        <?php if (0) : //$_product->isSaleable() && $this->hasOptions()): ?>
                            <p class="size">
                                <strong><?= $this->__('Selected size') ?>: </strong>
                                <span class="selectedSize"><?= $this->__('Choose size') ?></span>
                            </p>
                            <p class="availability">
                                <strong><?= $this->__('Availability:') ?> </strong>
                                <span class="availability choose"><?= $this->__('Choose size') ?></span>
                                <span class="availability true"><?= $this->__('In Stock') ?></span>
                                <span class="availability false"><?= $this->__('not available') ?></span>
                                <span class="info"><?= $this->__('Versandinfo'); ?></span>
                            </p>
                        <?php else: ?>
                            <?php if (1) : //$_product->isSaleable() && $stockItem->getQty() > 0): ?>
                                <p class="availability"><strong><?= $this->__('Availability:') ?></strong> <span class="true"><?= $this->__('In stock') ?></span> <span class="info"><?= $this->__('Versandinfo') ?></span></p>
                            <?php elseif (0) : //$_product->isSaleable() && $stockItem->getBackorders() > 0): ?>
                                <p class="availability"><strong><?= $this->__('Availability:') ?></strong> <span class="true"><?= $this->__('3-5 days after order') ?></span> <span class="info"><?= $this->__('Versandinfo'); ?></span></p>
                            <?php else: ?>
                                <?php $schemaOrgStockStatus = 'OutOfStock' ?>
                                <p class="availability"><strong><?= $this->__('Availability:') ?></strong> <span class="false"><?= $this->__('Out of stock') ?></span> <span class="info"><?= $this->__('Versandinfo'); ?></span></p>
                            <?php endif ?>
                        <?php endif ?>
                    </div>

                    <div class="price-information" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
                        {{snippet price}}
                    </div>
                </div>

                <div class="product-controls">
                    <?php if (1) : //$_product->isSaleable()): ?>
                        <fieldset class="selects">

                            <div class="input-box qty-box">
                                <select name="qty" id="qty">
                                    <?php for ($i = 1; $i <= $maxQty; $i++): ?>
                                        <option value="<?= $i; ?>"><?= $i; ?></option>
                                    <?php endfor; ?>
                                </select>
                            </div>
                            <div class="clearer"></div>
                        </fieldset>

                        <button type="submit" title="Add to Cart"><?= $this->__('Add to Cart') ?></button>
                    <?php endif ?>

                    <div class="clearer"></div>
                </div>
            </div>
        </div>
    </form>

    {{snippet all-models}}

    <div class="product-collateral">
        <ul class="tabs">
            <li><a href="#description"><?= $this->__('Description') ?></a></li>
            <li><a href="#additional-information"><?= $this->__('Additional Information') ?></a></li>
        </ul>
        <div id="description" class="tab-content" itemprop="description">
            <?= $this->getProductAttributeValue('description') ?>
        </div>
        <div id="additional-information" class="tab-content">
            [ TODO ]
        </div>
    </div>

    <div id="recently-viewed-products">
        <div class="heading"><?= $this->__('Your Recently Viewed') ?></div>
        <div class="swipe-container"></div>
    </div>

    <script type="text/javascript">

        var html = '<li style="background-image:url(\'/media/brands/brands-small/<?= $brandLogo ?>\')" class="item">';
        html += '<div class="grid-cell-container">';
        html += '<a href="<?php /* TODO: Product URL */ ?>" class="product-image"><img src="<?php /* TODO: 188x115 thumbnail URL */ ?>" width="188" height="115" alt="<?= $this->getProductAttributeValue('name') ?>" /></a>';
        html += '<h2 class="product-name"><a href="<?php /* TODO: Product URL */ ?>"><?= $this->getProductAttributeValue('name') ?></a></h2>';
        html += '<a href="<?php /* TODO: Product URL */ ?>">{{snippet price}}</a>';
        <?php if ($gender) : ?>
        html += '<p class="product-category"><a href="<?php /* TODO: Product URL */ ?>"><?= is_array($gender) ? implode(',', $gender) : $gender ?></a></p>';
        <?php endif; ?>
        <?php if ($save > 0) : ?>
        html += '<p class="you-save"><a href="<?php /* TODO: Product URL */ ?>"><?= $this->__('You save %s', '<strong>' . $save . '%</strong>'); ?></a></p>';
        <?php endif; ?>
        html += '</div>';
        html += '</li>';

        var product = {sku: '<?= $this->getProductId() ?>', html: html};

    </script>
</div>

<div id="fb-root"></div>
