<?php
/**
 * @var LizardsAndPumpkins\Product\Block\ProductBlock $this
 */
?>
<?php

$brand = $this->getFirstValueOfProductAttribute('brand');
$series = $this->getFirstValueOfProductAttribute('series');
$gender = $this->getImplodedValuesOfProductAttribute('gender', ', ');

?>
<div class="all-models">
    <h2 class="heading"><?= sprintf($this->__('Other %s %s models for %s'), $brand, $series, $gender) ?></h2>
    <div id="all-models" class="swipe-container"></div>
</div>
