<?php
/**
 * @var \LizardsAndPumpkins\Renderer\Block $this
 */
?>
<div class="footer-container">
    <div class="footer">
        <div class="footer-block">
            <div class="footer-block-title">21run.com</div>
            <ul id="footer-list-about">
                <li><a href="<?= $this->getBaseUrl() ?>about-us">Présentation</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>affiliate-program">Programme d'affiliation</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>terms-conditions">CGV</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>data-protection">Protection des données</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>cancellation">Droit de rétractation</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>imprint">Mentions légales</a></li>
            </ul>
        </div>
        <div class="footer-block">
            <div class="footer-block-title">Service à la clientèle</div>
            <ul>
                <li><a href="<?= $this->getBaseUrl() ?>contacts">Contact</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>service">Notre service</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>shipping">Expédition</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>conseils-grille-des-tailles/">Grille des tailles</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>exchange">Retour / Échanges</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>faq">FAQ</a></li>
            </ul>
        </div>
        <div class="footer-block">
            <div class="footer-block-title">Mon compte</div>
            <ul>
                <li><a href="<?= $this->getBaseUrl() ?>customer/account">Mon compte</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>sales/order/history">Statut de la commande</a></li>
                <li><a href="<?= $this->getBaseUrl() ?>newsletter">Newsletter</a></li>
            </ul>
        </div>
        <div class="footer-block-wide">
            <img src="<?= $this->getBaseUrl() ?>images/footer-banner-newsletter.png" alt="" />
            <img src="<?= $this->getBaseUrl() ?>images/footer-payment-methods.png" alt="" />
        </div>
        <div class="footer-block-info">
            <p>
                Tous les prix de nos produits sont exprimés TVA comprise et hors participation aux frais <a
                href="<?= $this->getBaseUrl() ?>shipping" target="_blank">d’expédition.</a> Les prix barrés
                correspondent aux prix de vente conseillés par le fabricant. Informations sur la société : L&amp;S
                Lauf- &amp; Sport Shop GmbH, Saarburger Ring 19-21, 68229 Mannheim – Pour plus d’informations sur
                notre service clients, veuillez consulter les mentions légales.
            </p>
        </div>
    </div>
</div>
