<?php

declare(strict_types=1);
/**
 * @var \LizardsAndPumpkins\Import\TemplateRendering\Block $this
 */
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?= $this->getChildOutput('title') ?></title>
<link type="text/css" rel="stylesheet" href="<?= $this->getBaseUrl() ?>css/<?= $this->getLayoutHandle() ?>.css" />
<script data-main="<?= $this->getBaseUrl() ?>js/<?= $this->getLayoutHandle() ?>" src="<?= $this->getBaseUrl() ?>js/lib/require.js"></script>
{{snippet head_container}}
