<?php

declare(strict_types=1);
/**
 * @var \LizardsAndPumpkins\Import\TemplateRendering\Block\ProductBlock $this
 */

use LizardsAndPumpkins\ProductDetail\Import\ConfigurableProductJsonSnippetRenderer;

?>
<h1><?= $this->getFirstValueOfProductAttribute('name') ?></h1>
<p><?= $this->getProductId() ?></p>

<script type="text/javascript">

    var product = <?= $this->getChildOutput('product_json') ?>,
        variation_attributes = <?= $this->getChildOutput(ConfigurableProductJsonSnippetRenderer::VARIATION_ATTRIBUTES_CODE) ?>,
        associated_products = <?= $this->getChildOutput(ConfigurableProductJsonSnippetRenderer::ASSOCIATED_PRODUCTS_CODE) ?>,
        translations = {{snippet translations}};

</script>
